---
- name: roasariosis | Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install ubuntu lang
  apt: pkg="{{item.apt}}"
  with_items: roasariosis_lang

- name: roasariosis | Install Preq
  apt: pkg="{{item}}" state=present
  with_items:
    - git
    - postgresql
    - postgresql-9.1
    - postgresql-contrib
    - python-psycopg2
    - apache2
    - php5
    - php5-pgsql

- name: roasariosis |  set permission for www 
  file:
    path="{{roasariosis_www}}"
    state=directory
    recurse=yes
    owner="{{roasariosis_user}}"

- name: roasariosis | Get roasariosis from git
  git:
    repo={{roasariosis_git}}
    dest="{{roasariosis_www}}"
    version="mobile"
  sudo_user: "{{roasariosis_user}}"

- name: roasariosis | Create postgresql user
  postgresql_user: 
     name="{{roasariosis_db_user}}"
     password="{{roasariosis_db_pass}}"
     role_attr_flags=SUPERUSER
  sudo_user: postgres

- name: roasariosis | Create postgresql Database ...
  postgresql_db:
    name="{{roasariosis_db}}"
    owner="{{roasariosis_db_user}}"
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
  sudo_user: postgres

- name: roasariosis | Deploy Config file
  template:
    src=config.inc.php.j2
    dest={{roasariosis_www}}/config.inc.php
    mode=0644
  notify: restart apache2

- name: Run SQL install
  shell: 
    psql rosariosis < {{roasariosis_www}}/rosariosis.sql  > /tmp/rosariosis.log
  sudo_user: postgres

- name: roasariosis | Enable SSL
  command:
    a2enmod ssl
  register: SSL
  changed_when: "'Enabling module ssl' in SSL.stdout"
  notify: restart apache2

- name: roasariosis | Deploy default apache site
  template:
    src=default.j2
    dest=/etc/apache2/sites-available/default
  notify: restart apache2
  when: roasariosis_www_manage

- name: roasariosis | Enable default apache site
  file:
    src=/etc/apache2/sites-available/default
    dest=/etc/apache2/sites-enabled/000-default
    state=link
  notify: restart apache2

- name: roasariosis | Download wkhtmlpdf
  get_url:
    url: "{{wkhtmlpdf_url}}"
    dest: "/tmp/{{wkhtmlpdf_files}}"
  register: wkhtmlpdf_reg

- name: roasariosis | unarchive wkhtmlpdf
  shell:
    mkdir /tmp/wkhtmltopdf && tar xvf /tmp/{{wkhtmlpdf_files}} -C /tmp/wkhtmltopdf --strip-components=1
  when: wkhtmlpdf_reg | changed

- name: roasariosis | move wkhtmlpdf bin 
  command:
    mv /tmp/wkhtmltopdf/bin/{{wkhtmlpdf_bin}} /usr/bin/{{wkhtmlpdf_bin}}
  when: wkhtmlpdf_reg | changed

- name: roasariosis | Executable
  file:
    path: "/usr/bin/{{wkhtmlpdf_bin}}"
    mode: 0755
  when: wkhtmlpdf_reg | changed